server:
  port: 8080
  servlet:
    context-path: /miso


spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/miso_demo?serverTimezone=Asia/Shanghai
    username: root
    password: root
  mvc:
    view:
      suffix: .jsp
      prefix: /
    hiddenmethod:
      filter:
        enabled: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    publisher-confirm-type: correlated  # 生产者发送消息到交换机 消息确认
    publisher-returns: true  # 交换机绑定到队列 消息确认

    listener:
      simple:
        acknowledge-mode: manual  #消息手动确认

        #削峰限流
        prefetch: 1  #消费者每次从队列中取几个消息
        concurrency: 3 #消费者数量
        max-concurrency: 10  #启动消费者最大数量
  redis:
    database: 0
    host: localhost
    port: 6379
    password:

  elasticsearch:
    uris: localhost:9200
    connection-timeout: 5s
    socket-timeout: 30s

mybatis-plus:
  global-config:
    db-config:
      id-type: auto

logging:
  file:
    path: D://misolog//miso_demo_log

  level:
    com.chixing: debug



